apps:
  - name: pgadmin-prd
    path: pgadmin
    values: values-prd.yaml
    targetRevision: main
    namespace: foo-prd
#  - name: pgadmin-acc
#    path: pgadmin
#    values: values-acc.yaml
#    targetRevision: main
#    namespace: foo-acc
  - name: pgadmin-tst
    path: pgadmin
    values: values-tst.yaml
    targetRevision: main
    namespace: foo-tst



  - name: postgres-tst
    path: postgres
    values: values-tst.yaml
    targetRevision: main
    namespace: foo-tst
#  - name: postgres-acc
#    path: postgres
#    values: values-acc.yaml
#    targetRevision: main
#    namespace: foo-acc
  - name: postgres-prd
    path: postgres
    values: values-prd.yaml
    targetRevision: main
    namespace: foo-prd